name: 'Travel & Transport'
favicon: null
layout_spectrum: 0.50117
typography_spectrum: 0.30211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bea6bb'
    - '#4f4448'
    - '#ffb200'
    - '#030301'
    - '#009e95'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.11540475487709045
purpose: []
